CREATE TABLE account
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    balance  NUMERIC(38, 2) NOT NULL,
    currency VARCHAR(3)     NOT NULL,
    owner_id BIGINT         NOT NULL,
    PRIMARY KEY (id)
);