CREATE TABLE transaction
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount            NUMERIC(38, 2)              NOT NULL,
    available_balance NUMERIC(38, 2)              NOT NULL,
    base_currency     VARCHAR(255)                NOT NULL,
    date_time         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    exchange_rate     NUMERIC(38, 2)              NOT NULL,
    from_account_id   BIGINT                      NOT NULL,
    residual_balance  NUMERIC(38, 2)              NOT NULL,
    status            VARCHAR(10)                 NOT NULL,
    target_currency   VARCHAR(255)                NOT NULL,
    to_account_id     BIGINT                      NOT NULL,
    PRIMARY KEY (id)
);